### ISSUE TITLE
Fleet crane-mcp deploy fails: @cloudflare/workers-types missing in crane-test-harness

### ISSUE THREAD

**Issue by SMDurgan** [venturecrane/crane-console#580]
## Symptom

`scripts/deploy-crane-mcp.sh` fails on every fleet machine (mbp27, think, mini) during the `npm run build` step with:

\`\`\`
> @venturecrane/crane-test-harness@0.1.0 build
> tsc

error TS2688: Cannot find type definition file for '@cloudflare/workers-types'.
  The file is in the program because:
    Entry point of type library '@cloudflare/workers-types' specified in compilerOptions
npm error Lifecycle script \`build\` failed with error:
npm error code 2
npm error path /home/smdurgan/dev/crane-console/packages/crane-test-harness
\`\`\`

All 3 fleet machines failed. Zero succeeded.

## Scope

- **Pre-existing**, not introduced by PR #579 (foundation/NODE_AUTH_TOKEN). That PR's file list is launcher + config + docs + templates; it does not touch `packages/crane-test-harness` or any workspace structure.
- **mac23 build succeeds** (verified during PR #579 verify + post-merge rebuild) — so either a Linux-specific issue, or the fleet machines have stale/partial `node_modules` that aren't hoisting `@cloudflare/workers-types` into `crane-test-harness`.

## Impact

- Fleet machines don't pick up crane-mcp launcher changes until this is resolved.
- Agents running on fleet machines (Gemini/Codex) that rely on the `NODE_AUTH_TOKEN` allowlist won't see the token until the fleet deploy succeeds.
- Claude Code agents on fleet machines are unaffected — they inherit `process.env` directly without an allowlist filter.

## Likely fixes (needs triage)

1. `crane-test-harness/tsconfig.json` or `package.json` references `@cloudflare/workers-types` at the workspace root but the workspace isn't installing it at the package level. Adding it as a direct devDep in `crane-test-harness` or adjusting `typeRoots`/`types` in its tsconfig.
2. Fleet machines may need a `rm -rf node_modules && npm install` at repo root before `deploy-crane-mcp.sh` runs, to force fresh hoisting.
3. Script could be hardened: run `npm install` at monorepo root before the per-package build, not just `cd packages/crane-mcp && npm install`.

## Verify after fix

\`\`\`bash
# On a fleet machine:
cd ~/dev/crane-console && git pull && npm install && npm run build
\`\`\`

Should complete all workspace builds without errors. Then retry `bash scripts/deploy-crane-mcp.sh` from mac23.

## Related

- PR #579 (foundation/NODE_AUTH_TOKEN) — merged at commit ff6d5f5, surfaced this during the standard post-merge fleet deploy.
